# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallimg', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('packet', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=256)),
                ('rated', models.CharField(max_length=256)),
                ('each', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('purchase', models.CharField(max_length=50)),
                ('act', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoodMilk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallimg', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('packet', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=256)),
                ('rated', models.CharField(max_length=256)),
                ('each', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('purchase', models.CharField(max_length=50)),
                ('act', models.CharField(max_length=50)),
            ],
        ),
    ]
