# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_auto_20181201_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetail',
            name='img1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
